-- MySQL Script generated by MySQL Workbench
-- Tue Oct 25 21:11:06 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema OpenBike
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OpenBike
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OpenBike` DEFAULT CHARACTER SET utf8 ;
USE `OpenBike` ;

-- -----------------------------------------------------
-- Table `OpenBike`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OpenBike`.`user` (
  `id_user` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `nickname` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `adress` TEXT NULL,
  `matricula` VARCHAR(45) NULL,
  `e-mail` VARCHAR(45) NULL,
  `nascimento` DATE NULL,
  `sexo` VARCHAR(1) NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OpenBike`.`station`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OpenBike`.`station` (
  `id_station` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `qnt_slots` INT NOT NULL,
  `adress` TEXT NOT NULL,
  `connected` TINYINT(1) NULL,
  PRIMARY KEY (`id_station`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OpenBike`.`bikes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OpenBike`.`bikes` (
  `id_bikes` INT NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  `cont` INT NOT NULL,
  PRIMARY KEY (`id_bikes`),
  CONSTRAINT `station_bike`
    FOREIGN KEY (`id_bikes`)
    REFERENCES `OpenBike`.`station` (`id_station`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_bike`
    FOREIGN KEY (`id_bikes`)
    REFERENCES `OpenBike`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OpenBike`.`emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OpenBike`.`emprestimo` (
  `id_emprestimo` INT NOT NULL,
  `date` DATE NOT NULL,
  `time` TIME NOT NULL,
  `type` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`id_emprestimo`),
  CONSTRAINT `emprestimo_user`
    FOREIGN KEY (`id_emprestimo`)
    REFERENCES `OpenBike`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `emprestimo_station`
    FOREIGN KEY ()
    REFERENCES `OpenBike`.`station` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `emprestimo_bike`
    FOREIGN KEY ()
    REFERENCES `OpenBike`.`bikes` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
